New log file opened at Wed Dec 16 16:05:17 CET 2015 by 2952@3dlab5
Taking next connection to: 55869
New client attempting to connect on port: 55870-55869
  Address = /141.37.31.55:55869
This client on port 55870 has uuid 21a646ab-e994-48c0-98dd-8e7f9b3eb3b7 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-21a646ab-e994-48c0-98dd-8e7f9b3eb3b7
Taking next connection to: 55869
New client attempting to connect on port: 55871-55869
  Address = /141.37.31.55:55869
Handshake exception on socket: 55871
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 55869
New client attempting to connect on port: 55872-55869
  Address = /141.37.31.55:55869
This client on port 55872 has uuid e93a546c-d168-4a58-8dd5-41214f9ebcca configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-21a646ab-e994-48c0-98dd-8e7f9b3eb3b7, activator-e93a546c-d168-4a58-8dd5-41214f9ebcca
Taking next connection to: 55869
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 55869
